Repository eslint/json, pull requests merged in 2024-10, with the labels that each got.

#27 feat: Add support for config comments
  .npmrc
  README.md
  package.json
  src/languages/json-source-code.js
  tests/languages/json-source-code.test.js
  tests/plugin/eslint.test.js
Labels: feature

#36 docs: Add sponsors to README
  .github/workflows/update-readme.yml
  README.md
  package.json
  tools/commit-readme.sh
  tools/update-readme.js
Labels: documentation, accepted

#40 test: Add `data` in tests for no-duplicate-keys rule
  tests/rules/no-duplicate-keys.test.js
Labels: chore, accepted

#42 feat: Add allowTrailingCommas option for JSONC
  README.md
  package.json
  src/languages/json-language.js
  tests/languages/json-language.test.js
Labels: feature, accepted

#44 ci: add Node.js v23
  .github/workflows/ci.yml
Labels: build
