Repository eslint/json, pull requests merged in 2024-11, with the labels that each got.

#30 feat: rule no-unsafe-values
  src/rules/no-unsafe-values.js
  tests/rules/no-unsafe-values.test.js
Labels: feature, contributor pool, accepted

#50 fix: Upgrade Momoa to fix parsing errors
  package.json
Labels: bug

#49 test: Add data into no-unsafe-values tests
  tests/rules/no-unsafe-values.test.js
Labels: chore

#51 feat: enable `no-unsafe-values` and add it to recommended configuration
  README.md
  src/index.js
Labels: feature

#53 test: Ensure all rules are exported
  tests/package/exports.js
  tests/plugin/eslint.test.js
Labels: chore

#60 chore: upgrade @eslint/plugin-kit@0.2.3
  package.json
Labels: chore

#65 fix: add type tests
  .github/workflows/ci.yml
  package.json
  src/index.js
  src/rules/no-duplicate-keys.js
  src/rules/no-empty-keys.js
  src/rules/no-unsafe-values.js
  tests/types/tsconfig.json
  tests/types/types.test.ts
Labels: bug

#63 feat: rule no-unnormalized-keys
  README.md
  src/index.js
  src/rules/no-unnormalized-keys.js
  tests/rules/no-unnormalized-keys.test.js
Labels: feature, accepted

#67 chore: Post release announcements across services
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/release-please.yml
  README.md
  package.json
Labels: chore, accepted
