Repository eslint/json, pull requests merged in 2024-12, with the labels that each got.

#70 test: Matching escaped and unescaped keys
  package.json
  tests/rules/no-duplicate-keys.test.js
Labels: contributor pool, chore

#69 feat: Add top-level-interop rule
  README.md
  src/index.js
  src/rules/top-level-interop.js
  tests/rules/top-level-interop.test.js
Labels: feature, contributor pool

#71 feat: Catch more unsafe numbers
  README.md
  src/rules/no-unsafe-values.js
  tests/rules/no-unsafe-values.test.js
Labels: feature, contributor pool

#74 ci: Add line breaks in social post announcement
  .github/workflows/release-please.yml
Labels: build, accepted
