Repository eslint/json, pull requests merged in 2024-07, with the labels that each got.

#1 feat: Add JSON plugin
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/change.yml
  .github/ISSUE_TEMPLATE/config.yml
  .github/ISSUE_TEMPLATE/docs.yml
  .github/ISSUE_TEMPLATE/new-rule.yml
  .github/ISSUE_TEMPLATE/rule-change.yml
  .github/PULL_REQUEST_TEMPLATE.md
  .github/workflows/ci.yml
  .github/workflows/release-please.yml
  .release-please-manifest.json
  CHANGELOG.md
  README.md
  eslint.config.js
  jsr.json
  package.json
  prettier.config.js
  release-please-config.json
  rollup.config.js
  src/index.js
  src/languages/json-language.js
  src/languages/json-source-code.js
  src/rules/no-duplicate-keys.js
  src/rules/no-empty-keys.js
  tests/languages/json-language.test.js
  tests/languages/json-source-code.test.js
  tests/rules/no-duplicate-keys.test.js
  tests/rules/no-empty-keys.test.js
  tools/dedupe-types.js
  tsconfig.esm.json
  tsconfig.json
Labels: feature

#3 ci: check formatting and jsr publish
  .github/workflows/ci.yml
  .prettierignore
  README.md
  package.json
Labels: build

#4 feat: Add JSONLanguage#visitorKeys
  package.json
  src/languages/json-language.js
  tests/languages/json-language.test.js
Labels: feature

#5 fix: Set initial release version in release-please-config.json
  release-please-config.json
Labels: bug

#6 chore: switch to `googleapis/release-please-action`
  .github/workflows/release-please.yml
Labels: chore

#7 fix: release-please (again)
  .github/workflows/release-please.yml
  release-please-config.json
Labels: bug

#8 chore: Update release-please pull request title
  release-please-config.json
Labels: chore

#10 build: Publish to JSR and update release-please config
  .github/workflows/release-please.yml
Labels: build

#9 ci: Test in Bun
  .github/workflows/bun-test.yml
  .gitignore
Labels: build

#11 docs: Include info about VS Code and package-lock.json
  README.md
Labels: documentation

#12 feat: Add meta info to plugin
  release-please-config.json
  src/index.js
Labels: feature, chore

#13 feat: Add getLoc and getRange to JSONSourceCode
  package.json
  src/languages/json-language.js
  src/languages/json-source-code.js
  tests/languages/json-source-code.test.js
Labels: feature

#15 feat: Add JSON5 support
  README.md
  package.json
  src/index.js
  src/languages/json-language.js
  src/rules/no-duplicate-keys.js
  src/rules/no-empty-keys.js
  tests/rules/no-duplicate-keys.test.js
  tests/rules/no-empty-keys.test.js
Labels: feature
