Repository eslint/json, pull requests merged in 2024-08, with the labels that each got.

#17 feat: Export internal constructs for other plugin authors
  src/index.js
  tests/package/exports.js
Labels: feature

#20 docs: Add FAQ and sponsors to README
  README.md
Labels: documentation

#23 docs: Add CommonJS example
  README.md
Labels: documentation

#22 refactor: Use @eslint/plugin-kit
  package.json
  src/languages/json-source-code.js
  tests/languages/json-source-code.test.js
Labels: chore, accepted
