Repository eslint/json, pull requests merged in 2025-05, with the labels that each got.

#94 docs: Update README to use defineConfig
  README.md
Labels: documentation

#96 refactor: switch JSONSourceCode to extend TextSourceCodeBase
  package.json
  src/languages/json-source-code.js
  tests/types/types.test.ts
Labels: contributor pool, chore, accepted

#97 docs: fix a typo and add links
  README.md
Labels: documentation, accepted

#93 chore: use `defineConfig` and `globalIgnores` in ESLint config
  eslint.config.js
  package.json
Labels: chore, accepted

#98 ci: run tests in Node.js 24
  .github/workflows/ci.yml
Labels: build

#100 docs: Add editor/IDE setup to README
  README.md
Labels: documentation

#101 build: Generate social media changelog
  .github/workflows/release-please.yml
Labels: build, accepted

#103 chore: cleanup `.gitignore`
  .gitignore
Labels: chore, accepted
