Repository eslint/json, pull requests merged in 2025-03, with the labels that each got.

#84 feat: Add `types` to exports
  package.json
Labels: feature, contributor pool

#86 fix: Update types and apply to all rules
  src/rules/no-duplicate-keys.js
  src/rules/no-empty-keys.js
  src/rules/no-unnormalized-keys.js
  src/rules/no-unsafe-values.js
  src/rules/sort-keys.js
  src/rules/top-level-interop.js
  src/types.ts
Labels: bug, accepted

#89 test: re-enable `ESLint.Plugin` type test
  package.json
  tests/types/types.test.ts
Labels: chore

#88 fix: Update `types.ts` for compatibility with `verbatimModuleSyntax`
  src/types.ts
  tests/types/tsconfig.json
  tests/types/types.test.ts
Labels: bug, contributor pool, accepted
