Repository eslint/json, pull requests merged in 2025-07, with the labels that each got.

#112 feat: Add token methods to JSONSourceCode
  .gitignore
  docs/rules/no-unnormalized-keys.md
  src/languages/json-source-code.js
  tests/languages/json-source-code.test.js
Labels: feature, accepted

#119 ci: Fix type issues
  tsconfig.json
Labels: build

#120 docs: remove `PULL_REQUEST_TEMPLATE.md` in favor of centralized template
  .github/PULL_REQUEST_TEMPLATE.md
Labels: documentation

#118 build: automate generation of recommended rules config
  .github/workflows/ci.yml
  .github/workflows/release-please.yml
  .gitignore
  eslint.config.js
  package.json
  src/index.js
  tools/build-rules.js
Labels: build, chore, accepted

#121 refactor: use `CustomRuleDefinitionType` in `JSONRuleDefinition`
  package.json
  src/types.ts
Labels: chore, accepted

#123 refactor: add missing type annotations to variables
  src/languages/json-source-code.js
Labels: chore
