Repository eslint/json, pull requests merged in 2025-08, with the labels that each got.

#132 fix: allow any type for `meta.docs.recommended` in custom rules
  package.json
  tests/types/types.test.ts
Labels: bug, accepted

#131 ci: add `stale` and fix `add-to-triage`
  .github/workflows/add-to-triage.yml
  .github/workflows/stale.yml
Labels: build, accepted

#128 refactor: update eslint-config-eslint
  package.json
  src/languages/json-source-code.js
  src/rules/no-unsafe-values.js
  tools/dedupe-types.js
  tools/update-readme.js
Labels: contributor pool, chore, accepted
