Repository eslint/json, pull requests merged in 2025-04, with the labels that each got.

#91 feat!: Update package types for better reuse
  package.json
  rollup.config.js
  src/index.js
  src/languages/json-language.js
  src/languages/json-source-code.js
  src/rules/no-duplicate-keys.js
  src/rules/no-empty-keys.js
  src/rules/no-unnormalized-keys.js
  src/rules/no-unsafe-values.js
  src/rules/sort-keys.js
  src/rules/top-level-interop.js
  src/types.ts
  tools/build-cts.js
  tools/dedupe-types.js
Labels: feature, accepted, breaking

#92 test: create tests for `JSONRuleDefinition`
  tests/types/types.test.ts
Labels: chore, accepted

#95 docs: fixed a typo in `top-level-interop.js`
  src/rules/top-level-interop.js
Labels: documentation
